#!/bin/sh
set -e

branch_f1r3fly=main
branch_scalapb=master
out_dir=protobuf
tmp_dir=$(mktemp -d)
repo_dir=$(pwd)

cleanup() {
    rm -rf "$tmp_dir"
}

trap cleanup EXIT HUP INT TERM

mkdir -p "$out_dir"

# Clone f1r3node repo (sparse checkout for just protobuf files)
echo "Fetching protobufs from F1R3FLY-io/f1r3node..."
git clone --depth 1 --filter=blob:none --sparse \
    https://github.com/F1R3FLY-io/f1r3node.git \
    --branch $branch_f1r3fly \
    "$tmp_dir/f1r3node"
cd "$tmp_dir/f1r3node"
git sparse-checkout set models/src/main/protobuf
cp -r models/src/main/protobuf/* "$repo_dir/$out_dir/"
cd "$repo_dir"

# Clone ScalaPB repo (sparse checkout for just protobuf files)
echo "Fetching protobufs from scalapb/ScalaPB..."
git clone --depth 1 --filter=blob:none --sparse \
    https://github.com/scalapb/ScalaPB.git \
    --branch $branch_scalapb \
    "$tmp_dir/scalapb"
cd "$tmp_dir/scalapb"
git sparse-checkout set protobuf
cp -r protobuf/* "$repo_dir/$out_dir/"
cd "$repo_dir"

echo "Done! Protobufs updated in $out_dir/"
