"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
*
The main API is `DeployService`.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import RhoTypes_pb2 as _RhoTypes_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HasBlockRequestProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HASH_FIELD_NUMBER: _builtins.int
    hash: _builtins.bytes
    def __init__(
        self,
        *,
        hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hash", b"hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HasBlockRequestProto: _TypeAlias = HasBlockRequestProto  # noqa: Y015

@_typing.final
class HasBlockProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HASH_FIELD_NUMBER: _builtins.int
    hash: _builtins.bytes
    def __init__(
        self,
        *,
        hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hash", b"hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HasBlockProto: _TypeAlias = HasBlockProto  # noqa: Y015

@_typing.final
class BlockRequestProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HASH_FIELD_NUMBER: _builtins.int
    hash: _builtins.bytes
    def __init__(
        self,
        *,
        hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hash", b"hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BlockRequestProto: _TypeAlias = BlockRequestProto  # noqa: Y015

@_typing.final
class ForkChoiceTipRequestProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ForkChoiceTipRequestProto: _TypeAlias = ForkChoiceTipRequestProto  # noqa: Y015

@_typing.final
class ApprovedBlockCandidateProto(_message.Message):
    """---------- Signing Protocol ---------"""

    DESCRIPTOR: _descriptor.Descriptor

    BLOCK_FIELD_NUMBER: _builtins.int
    REQUIREDSIGS_FIELD_NUMBER: _builtins.int
    requiredSigs: _builtins.int
    @_builtins.property
    def block(self) -> Global___BlockMessageProto: ...
    def __init__(
        self,
        *,
        block: Global___BlockMessageProto | None = ...,
        requiredSigs: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["block", b"block"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["block", b"block", "requiredSigs", b"requiredSigs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApprovedBlockCandidateProto: _TypeAlias = ApprovedBlockCandidateProto  # noqa: Y015

@_typing.final
class UnapprovedBlockProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CANDIDATE_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    DURATION_FIELD_NUMBER: _builtins.int
    timestamp: _builtins.int
    duration: _builtins.int
    @_builtins.property
    def candidate(self) -> Global___ApprovedBlockCandidateProto: ...
    def __init__(
        self,
        *,
        candidate: Global___ApprovedBlockCandidateProto | None = ...,
        timestamp: _builtins.int = ...,
        duration: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["candidate", b"candidate"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["candidate", b"candidate", "duration", b"duration", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnapprovedBlockProto: _TypeAlias = UnapprovedBlockProto  # noqa: Y015

@_typing.final
class Signature(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PUBLICKEY_FIELD_NUMBER: _builtins.int
    ALGORITHM_FIELD_NUMBER: _builtins.int
    SIG_FIELD_NUMBER: _builtins.int
    publicKey: _builtins.bytes
    algorithm: _builtins.str
    sig: _builtins.bytes
    def __init__(
        self,
        *,
        publicKey: _builtins.bytes = ...,
        algorithm: _builtins.str = ...,
        sig: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["algorithm", b"algorithm", "publicKey", b"publicKey", "sig", b"sig"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Signature: _TypeAlias = Signature  # noqa: Y015

@_typing.final
class BlockApprovalProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CANDIDATE_FIELD_NUMBER: _builtins.int
    SIG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def candidate(self) -> Global___ApprovedBlockCandidateProto: ...
    @_builtins.property
    def sig(self) -> Global___Signature: ...
    def __init__(
        self,
        *,
        candidate: Global___ApprovedBlockCandidateProto | None = ...,
        sig: Global___Signature | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["candidate", b"candidate", "sig", b"sig"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["candidate", b"candidate", "sig", b"sig"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BlockApprovalProto: _TypeAlias = BlockApprovalProto  # noqa: Y015

@_typing.final
class ApprovedBlockProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CANDIDATE_FIELD_NUMBER: _builtins.int
    SIGS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def candidate(self) -> Global___ApprovedBlockCandidateProto: ...
    @_builtins.property
    def sigs(self) -> _containers.RepeatedCompositeFieldContainer[Global___Signature]: ...
    def __init__(
        self,
        *,
        candidate: Global___ApprovedBlockCandidateProto | None = ...,
        sigs: _abc.Iterable[Global___Signature] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["candidate", b"candidate"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["candidate", b"candidate", "sigs", b"sigs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApprovedBlockProto: _TypeAlias = ApprovedBlockProto  # noqa: Y015

@_typing.final
class ApprovedBlockRequestProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: _builtins.int
    TRIMSTATE_FIELD_NUMBER: _builtins.int
    identifier: _builtins.str
    trimState: _builtins.bool
    def __init__(
        self,
        *,
        identifier: _builtins.str = ...,
        trimState: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["identifier", b"identifier", "trimState", b"trimState"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApprovedBlockRequestProto: _TypeAlias = ApprovedBlockRequestProto  # noqa: Y015

@_typing.final
class NoApprovedBlockAvailableProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: _builtins.int
    NODEIDENTIFER_FIELD_NUMBER: _builtins.int
    identifier: _builtins.str
    nodeIdentifer: _builtins.str
    def __init__(
        self,
        *,
        identifier: _builtins.str = ...,
        nodeIdentifer: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["identifier", b"identifier", "nodeIdentifer", b"nodeIdentifer"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NoApprovedBlockAvailableProto: _TypeAlias = NoApprovedBlockAvailableProto  # noqa: Y015

@_typing.final
class BlockMessageProto(_message.Message):
    """------- End Signing Protocol --------

    --------- Core Protocol  --------
    """

    DESCRIPTOR: _descriptor.Descriptor

    BLOCKHASH_FIELD_NUMBER: _builtins.int
    HEADER_FIELD_NUMBER: _builtins.int
    BODY_FIELD_NUMBER: _builtins.int
    JUSTIFICATIONS_FIELD_NUMBER: _builtins.int
    SENDER_FIELD_NUMBER: _builtins.int
    SEQNUM_FIELD_NUMBER: _builtins.int
    SIG_FIELD_NUMBER: _builtins.int
    SIGALGORITHM_FIELD_NUMBER: _builtins.int
    SHARDID_FIELD_NUMBER: _builtins.int
    EXTRABYTES_FIELD_NUMBER: _builtins.int
    blockHash: _builtins.bytes
    """obtained by hashing the information in the header"""
    sender: _builtins.bytes
    """public key of the validator that created the block"""
    seqNum: _builtins.int
    """number of blocks created by the validator"""
    sig: _builtins.bytes
    """signature generated by signing `hash(hash(justification) concat blockHash)`."""
    sigAlgorithm: _builtins.str
    """name of the algorithm used to sign"""
    shardId: _builtins.str
    """identifier of the shard where the block was created"""
    extraBytes: _builtins.bytes
    @_builtins.property
    def header(self) -> Global___HeaderProto: ...
    @_builtins.property
    def body(self) -> Global___BodyProto: ...
    @_builtins.property
    def justifications(self) -> _containers.RepeatedCompositeFieldContainer[Global___JustificationProto]:
        """map of all validators to latest blocks based on current view"""

    def __init__(
        self,
        *,
        blockHash: _builtins.bytes = ...,
        header: Global___HeaderProto | None = ...,
        body: Global___BodyProto | None = ...,
        justifications: _abc.Iterable[Global___JustificationProto] | None = ...,
        sender: _builtins.bytes = ...,
        seqNum: _builtins.int = ...,
        sig: _builtins.bytes = ...,
        sigAlgorithm: _builtins.str = ...,
        shardId: _builtins.str = ...,
        extraBytes: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["body", b"body", "header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blockHash", b"blockHash", "body", b"body", "extraBytes", b"extraBytes", "header", b"header", "justifications", b"justifications", "sender", b"sender", "seqNum", b"seqNum", "shardId", b"shardId", "sig", b"sig", "sigAlgorithm", b"sigAlgorithm"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BlockMessageProto: _TypeAlias = BlockMessageProto  # noqa: Y015

@_typing.final
class BlockHashMessageProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HASH_FIELD_NUMBER: _builtins.int
    BLOCKCREATOR_FIELD_NUMBER: _builtins.int
    hash: _builtins.bytes
    blockCreator: _builtins.bytes
    def __init__(
        self,
        *,
        hash: _builtins.bytes = ...,
        blockCreator: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blockCreator", b"blockCreator", "hash", b"hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BlockHashMessageProto: _TypeAlias = BlockHashMessageProto  # noqa: Y015

@_typing.final
class BlockMetadataInternal(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BLOCKHASH_FIELD_NUMBER: _builtins.int
    PARENTS_FIELD_NUMBER: _builtins.int
    SENDER_FIELD_NUMBER: _builtins.int
    JUSTIFICATIONS_FIELD_NUMBER: _builtins.int
    BONDS_FIELD_NUMBER: _builtins.int
    BLOCKNUM_FIELD_NUMBER: _builtins.int
    SEQNUM_FIELD_NUMBER: _builtins.int
    INVALID_FIELD_NUMBER: _builtins.int
    DIRECTLYFINALIZED_FIELD_NUMBER: _builtins.int
    FINALIZED_FIELD_NUMBER: _builtins.int
    blockHash: _builtins.bytes
    sender: _builtins.bytes
    blockNum: _builtins.int
    seqNum: _builtins.int
    invalid: _builtins.bool
    """whether the block was marked as invalid"""
    directlyFinalized: _builtins.bool
    """whether the block has been last finalized block (LFB)"""
    finalized: _builtins.bool
    """whether the block is finalized"""
    @_builtins.property
    def parents(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    @_builtins.property
    def justifications(self) -> _containers.RepeatedCompositeFieldContainer[Global___JustificationProto]: ...
    @_builtins.property
    def bonds(self) -> _containers.RepeatedCompositeFieldContainer[Global___BondProto]: ...
    def __init__(
        self,
        *,
        blockHash: _builtins.bytes = ...,
        parents: _abc.Iterable[_builtins.bytes] | None = ...,
        sender: _builtins.bytes = ...,
        justifications: _abc.Iterable[Global___JustificationProto] | None = ...,
        bonds: _abc.Iterable[Global___BondProto] | None = ...,
        blockNum: _builtins.int = ...,
        seqNum: _builtins.int = ...,
        invalid: _builtins.bool = ...,
        directlyFinalized: _builtins.bool = ...,
        finalized: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blockHash", b"blockHash", "blockNum", b"blockNum", "bonds", b"bonds", "directlyFinalized", b"directlyFinalized", "finalized", b"finalized", "invalid", b"invalid", "justifications", b"justifications", "parents", b"parents", "sender", b"sender", "seqNum", b"seqNum"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BlockMetadataInternal: _TypeAlias = BlockMetadataInternal  # noqa: Y015

@_typing.final
class HeaderProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PARENTSHASHLIST_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    EXTRABYTES_FIELD_NUMBER: _builtins.int
    timestamp: _builtins.int
    version: _builtins.int
    extraBytes: _builtins.bytes
    @_builtins.property
    def parentsHashList(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]:
        """list of parent block hashes"""

    def __init__(
        self,
        *,
        parentsHashList: _abc.Iterable[_builtins.bytes] | None = ...,
        timestamp: _builtins.int = ...,
        version: _builtins.int = ...,
        extraBytes: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["extraBytes", b"extraBytes", "parentsHashList", b"parentsHashList", "timestamp", b"timestamp", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HeaderProto: _TypeAlias = HeaderProto  # noqa: Y015

@_typing.final
class DeployDataProto(_message.Message):
    """*
    Note: deploys are uniquely keyed by `user`, `timestamp`.

    **TODO**: details of signatures and payment. See RHOL-781
    """

    DESCRIPTOR: _descriptor.Descriptor

    DEPLOYER_FIELD_NUMBER: _builtins.int
    TERM_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    SIG_FIELD_NUMBER: _builtins.int
    SIGALGORITHM_FIELD_NUMBER: _builtins.int
    PHLOPRICE_FIELD_NUMBER: _builtins.int
    PHLOLIMIT_FIELD_NUMBER: _builtins.int
    VALIDAFTERBLOCKNUMBER_FIELD_NUMBER: _builtins.int
    SHARDID_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    deployer: _builtins.bytes
    """public key"""
    term: _builtins.str
    """rholang source code to deploy (will be parsed into `Par`)"""
    timestamp: _builtins.int
    """millisecond timestamp"""
    sig: _builtins.bytes
    """signature of (hash(term) + timestamp) using private key"""
    sigAlgorithm: _builtins.str
    """name of the algorithm used to sign"""
    phloPrice: _builtins.int
    """phlo price"""
    phloLimit: _builtins.int
    """phlo limit for the deployment"""
    validAfterBlockNumber: _builtins.int
    shardId: _builtins.str
    """shard ID to prevent replay of deploys between shards"""
    language: _builtins.str
    """language (rholang or metta) of the source code"""
    def __init__(
        self,
        *,
        deployer: _builtins.bytes = ...,
        term: _builtins.str = ...,
        timestamp: _builtins.int = ...,
        sig: _builtins.bytes = ...,
        sigAlgorithm: _builtins.str = ...,
        phloPrice: _builtins.int = ...,
        phloLimit: _builtins.int = ...,
        validAfterBlockNumber: _builtins.int = ...,
        shardId: _builtins.str = ...,
        language: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deployer", b"deployer", "language", b"language", "phloLimit", b"phloLimit", "phloPrice", b"phloPrice", "shardId", b"shardId", "sig", b"sig", "sigAlgorithm", b"sigAlgorithm", "term", b"term", "timestamp", b"timestamp", "validAfterBlockNumber", b"validAfterBlockNumber"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeployDataProto: _TypeAlias = DeployDataProto  # noqa: Y015

@_typing.final
class ProcessedDeployProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEPLOY_FIELD_NUMBER: _builtins.int
    COST_FIELD_NUMBER: _builtins.int
    DEPLOYLOG_FIELD_NUMBER: _builtins.int
    ERRORED_FIELD_NUMBER: _builtins.int
    SYSTEMDEPLOYERROR_FIELD_NUMBER: _builtins.int
    errored: _builtins.bool
    """true if deploy encountered a user error"""
    systemDeployError: _builtins.str
    @_builtins.property
    def deploy(self) -> Global___DeployDataProto: ...
    @_builtins.property
    def cost(self) -> _RhoTypes_pb2.PCost: ...
    @_builtins.property
    def deployLog(self) -> _containers.RepeatedCompositeFieldContainer[Global___EventProto]:
        """the new terms and comm. rule reductions from this deploy"""

    def __init__(
        self,
        *,
        deploy: Global___DeployDataProto | None = ...,
        cost: _RhoTypes_pb2.PCost | None = ...,
        deployLog: _abc.Iterable[Global___EventProto] | None = ...,
        errored: _builtins.bool = ...,
        systemDeployError: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cost", b"cost", "deploy", b"deploy"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cost", b"cost", "deploy", b"deploy", "deployLog", b"deployLog", "errored", b"errored", "systemDeployError", b"systemDeployError"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProcessedDeployProto: _TypeAlias = ProcessedDeployProto  # noqa: Y015

@_typing.final
class SlashSystemDeployDataProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INVALIDBLOCKHASH_FIELD_NUMBER: _builtins.int
    ISSUERPUBLICKEY_FIELD_NUMBER: _builtins.int
    invalidBlockHash: _builtins.bytes
    issuerPublicKey: _builtins.bytes
    def __init__(
        self,
        *,
        invalidBlockHash: _builtins.bytes = ...,
        issuerPublicKey: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["invalidBlockHash", b"invalidBlockHash", "issuerPublicKey", b"issuerPublicKey"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SlashSystemDeployDataProto: _TypeAlias = SlashSystemDeployDataProto  # noqa: Y015

@_typing.final
class CloseBlockSystemDeployDataProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___CloseBlockSystemDeployDataProto: _TypeAlias = CloseBlockSystemDeployDataProto  # noqa: Y015

@_typing.final
class SystemDeployDataProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SLASHSYSTEMDEPLOY_FIELD_NUMBER: _builtins.int
    CLOSEBLOCKSYSTEMDEPLOY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def slashSystemDeploy(self) -> Global___SlashSystemDeployDataProto: ...
    @_builtins.property
    def closeBlockSystemDeploy(self) -> Global___CloseBlockSystemDeployDataProto: ...
    def __init__(
        self,
        *,
        slashSystemDeploy: Global___SlashSystemDeployDataProto | None = ...,
        closeBlockSystemDeploy: Global___CloseBlockSystemDeployDataProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["closeBlockSystemDeploy", b"closeBlockSystemDeploy", "slashSystemDeploy", b"slashSystemDeploy", "systemDeploy", b"systemDeploy"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["closeBlockSystemDeploy", b"closeBlockSystemDeploy", "slashSystemDeploy", b"slashSystemDeploy", "systemDeploy", b"systemDeploy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_systemDeploy: _TypeAlias = _typing.Literal["slashSystemDeploy", "closeBlockSystemDeploy"]  # noqa: Y015
    _WhichOneofArgType_systemDeploy: _TypeAlias = _typing.Literal["systemDeploy", b"systemDeploy"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_systemDeploy) -> _WhichOneofReturnType_systemDeploy | None: ...

Global___SystemDeployDataProto: _TypeAlias = SystemDeployDataProto  # noqa: Y015

@_typing.final
class ProcessedSystemDeployProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYSTEMDEPLOY_FIELD_NUMBER: _builtins.int
    DEPLOYLOG_FIELD_NUMBER: _builtins.int
    ERRORMSG_FIELD_NUMBER: _builtins.int
    errorMsg: _builtins.str
    @_builtins.property
    def systemDeploy(self) -> Global___SystemDeployDataProto: ...
    @_builtins.property
    def deployLog(self) -> _containers.RepeatedCompositeFieldContainer[Global___EventProto]: ...
    def __init__(
        self,
        *,
        systemDeploy: Global___SystemDeployDataProto | None = ...,
        deployLog: _abc.Iterable[Global___EventProto] | None = ...,
        errorMsg: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["systemDeploy", b"systemDeploy"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deployLog", b"deployLog", "errorMsg", b"errorMsg", "systemDeploy", b"systemDeploy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProcessedSystemDeployProto: _TypeAlias = ProcessedSystemDeployProto  # noqa: Y015

@_typing.final
class BodyProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATE_FIELD_NUMBER: _builtins.int
    DEPLOYS_FIELD_NUMBER: _builtins.int
    SYSTEMDEPLOYS_FIELD_NUMBER: _builtins.int
    EXTRABYTES_FIELD_NUMBER: _builtins.int
    REJECTEDDEPLOYS_FIELD_NUMBER: _builtins.int
    extraBytes: _builtins.bytes
    @_builtins.property
    def state(self) -> Global___RChainStateProto: ...
    @_builtins.property
    def deploys(self) -> _containers.RepeatedCompositeFieldContainer[Global___ProcessedDeployProto]: ...
    @_builtins.property
    def systemDeploys(self) -> _containers.RepeatedCompositeFieldContainer[Global___ProcessedSystemDeployProto]: ...
    @_builtins.property
    def rejectedDeploys(self) -> _containers.RepeatedCompositeFieldContainer[Global___RejectedDeployProto]: ...
    def __init__(
        self,
        *,
        state: Global___RChainStateProto | None = ...,
        deploys: _abc.Iterable[Global___ProcessedDeployProto] | None = ...,
        systemDeploys: _abc.Iterable[Global___ProcessedSystemDeployProto] | None = ...,
        extraBytes: _builtins.bytes = ...,
        rejectedDeploys: _abc.Iterable[Global___RejectedDeployProto] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deploys", b"deploys", "extraBytes", b"extraBytes", "rejectedDeploys", b"rejectedDeploys", "state", b"state", "systemDeploys", b"systemDeploys"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BodyProto: _TypeAlias = BodyProto  # noqa: Y015

@_typing.final
class RejectedDeployProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SIG_FIELD_NUMBER: _builtins.int
    sig: _builtins.bytes
    def __init__(
        self,
        *,
        sig: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sig", b"sig"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RejectedDeployProto: _TypeAlias = RejectedDeployProto  # noqa: Y015

@_typing.final
class JustificationProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALIDATOR_FIELD_NUMBER: _builtins.int
    LATESTBLOCKHASH_FIELD_NUMBER: _builtins.int
    validator: _builtins.bytes
    latestBlockHash: _builtins.bytes
    def __init__(
        self,
        *,
        validator: _builtins.bytes = ...,
        latestBlockHash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["latestBlockHash", b"latestBlockHash", "validator", b"validator"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___JustificationProto: _TypeAlias = JustificationProto  # noqa: Y015

@_typing.final
class RChainStateProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRESTATEHASH_FIELD_NUMBER: _builtins.int
    POSTSTATEHASH_FIELD_NUMBER: _builtins.int
    BONDS_FIELD_NUMBER: _builtins.int
    BLOCKNUMBER_FIELD_NUMBER: _builtins.int
    preStateHash: _builtins.bytes
    """hash of the tuplespace contents before new deploys"""
    postStateHash: _builtins.bytes
    """hash of the tuplespace contents after new deploys"""
    blockNumber: _builtins.int
    @_builtins.property
    def bonds(self) -> _containers.RepeatedCompositeFieldContainer[Global___BondProto]:
        """Internals of what will be the "blessed" PoS contract
        (which will be part of the tuplespace in the real implementation).
        """

    def __init__(
        self,
        *,
        preStateHash: _builtins.bytes = ...,
        postStateHash: _builtins.bytes = ...,
        bonds: _abc.Iterable[Global___BondProto] | None = ...,
        blockNumber: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blockNumber", b"blockNumber", "bonds", b"bonds", "postStateHash", b"postStateHash", "preStateHash", b"preStateHash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RChainStateProto: _TypeAlias = RChainStateProto  # noqa: Y015

@_typing.final
class EventProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRODUCE_FIELD_NUMBER: _builtins.int
    CONSUME_FIELD_NUMBER: _builtins.int
    COMM_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def produce(self) -> Global___ProduceEventProto: ...
    @_builtins.property
    def consume(self) -> Global___ConsumeEventProto: ...
    @_builtins.property
    def comm(self) -> Global___CommEventProto: ...
    def __init__(
        self,
        *,
        produce: Global___ProduceEventProto | None = ...,
        consume: Global___ConsumeEventProto | None = ...,
        comm: Global___CommEventProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["comm", b"comm", "consume", b"consume", "event_instance", b"event_instance", "produce", b"produce"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["comm", b"comm", "consume", b"consume", "event_instance", b"event_instance", "produce", b"produce"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event_instance: _TypeAlias = _typing.Literal["produce", "consume", "comm"]  # noqa: Y015
    _WhichOneofArgType_event_instance: _TypeAlias = _typing.Literal["event_instance", b"event_instance"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event_instance) -> _WhichOneofReturnType_event_instance | None: ...

Global___EventProto: _TypeAlias = EventProto  # noqa: Y015

@_typing.final
class ProduceEventProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHANNELSHASH_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    PERSISTENT_FIELD_NUMBER: _builtins.int
    TIMESREPEATED_FIELD_NUMBER: _builtins.int
    ISDETERMINISTIC_FIELD_NUMBER: _builtins.int
    OUTPUTVALUE_FIELD_NUMBER: _builtins.int
    FAILED_FIELD_NUMBER: _builtins.int
    channelsHash: _builtins.bytes
    hash: _builtins.bytes
    persistent: _builtins.bool
    timesRepeated: _builtins.int
    isDeterministic: _builtins.bool
    failed: _builtins.bool
    @_builtins.property
    def outputValue(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    def __init__(
        self,
        *,
        channelsHash: _builtins.bytes = ...,
        hash: _builtins.bytes = ...,
        persistent: _builtins.bool = ...,
        timesRepeated: _builtins.int = ...,
        isDeterministic: _builtins.bool = ...,
        outputValue: _abc.Iterable[_builtins.bytes] | None = ...,
        failed: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channelsHash", b"channelsHash", "failed", b"failed", "hash", b"hash", "isDeterministic", b"isDeterministic", "outputValue", b"outputValue", "persistent", b"persistent", "timesRepeated", b"timesRepeated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProduceEventProto: _TypeAlias = ProduceEventProto  # noqa: Y015

@_typing.final
class ConsumeEventProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHANNELSHASHES_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    PERSISTENT_FIELD_NUMBER: _builtins.int
    hash: _builtins.bytes
    persistent: _builtins.bool
    @_builtins.property
    def channelsHashes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    def __init__(
        self,
        *,
        channelsHashes: _abc.Iterable[_builtins.bytes] | None = ...,
        hash: _builtins.bytes = ...,
        persistent: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channelsHashes", b"channelsHashes", "hash", b"hash", "persistent", b"persistent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConsumeEventProto: _TypeAlias = ConsumeEventProto  # noqa: Y015

@_typing.final
class CommEventProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONSUME_FIELD_NUMBER: _builtins.int
    PRODUCES_FIELD_NUMBER: _builtins.int
    PEEKS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def consume(self) -> Global___ConsumeEventProto: ...
    @_builtins.property
    def produces(self) -> _containers.RepeatedCompositeFieldContainer[Global___ProduceEventProto]: ...
    @_builtins.property
    def peeks(self) -> _containers.RepeatedCompositeFieldContainer[Global___PeekProto]: ...
    def __init__(
        self,
        *,
        consume: Global___ConsumeEventProto | None = ...,
        produces: _abc.Iterable[Global___ProduceEventProto] | None = ...,
        peeks: _abc.Iterable[Global___PeekProto] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["consume", b"consume"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["consume", b"consume", "peeks", b"peeks", "produces", b"produces"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CommEventProto: _TypeAlias = CommEventProto  # noqa: Y015

@_typing.final
class PeekProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHANNELINDEX_FIELD_NUMBER: _builtins.int
    channelIndex: _builtins.int
    def __init__(
        self,
        *,
        channelIndex: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channelIndex", b"channelIndex"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PeekProto: _TypeAlias = PeekProto  # noqa: Y015

@_typing.final
class BondProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALIDATOR_FIELD_NUMBER: _builtins.int
    STAKE_FIELD_NUMBER: _builtins.int
    validator: _builtins.bytes
    stake: _builtins.int
    def __init__(
        self,
        *,
        validator: _builtins.bytes = ...,
        stake: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stake", b"stake", "validator", b"validator"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BondProto: _TypeAlias = BondProto  # noqa: Y015

@_typing.final
class StoreNodeKeyProto(_message.Message):
    """--------- Last finalized state  --------"""

    DESCRIPTOR: _descriptor.Descriptor

    HASH_FIELD_NUMBER: _builtins.int
    INDEX_FIELD_NUMBER: _builtins.int
    hash: _builtins.bytes
    index: _builtins.int
    def __init__(
        self,
        *,
        hash: _builtins.bytes = ...,
        index: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hash", b"hash", "index", b"index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StoreNodeKeyProto: _TypeAlias = StoreNodeKeyProto  # noqa: Y015

@_typing.final
class StoreItemsMessageRequestProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STARTPATH_FIELD_NUMBER: _builtins.int
    SKIP_FIELD_NUMBER: _builtins.int
    TAKE_FIELD_NUMBER: _builtins.int
    skip: _builtins.int
    take: _builtins.int
    @_builtins.property
    def startPath(self) -> _containers.RepeatedCompositeFieldContainer[Global___StoreNodeKeyProto]: ...
    def __init__(
        self,
        *,
        startPath: _abc.Iterable[Global___StoreNodeKeyProto] | None = ...,
        skip: _builtins.int = ...,
        take: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["skip", b"skip", "startPath", b"startPath", "take", b"take"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StoreItemsMessageRequestProto: _TypeAlias = StoreItemsMessageRequestProto  # noqa: Y015

@_typing.final
class StoreItemProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.bytes
    value: _builtins.bytes
    def __init__(
        self,
        *,
        key: _builtins.bytes = ...,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StoreItemProto: _TypeAlias = StoreItemProto  # noqa: Y015

@_typing.final
class StoreItemsMessageProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STARTPATH_FIELD_NUMBER: _builtins.int
    LASTPATH_FIELD_NUMBER: _builtins.int
    HISTORYITEMS_FIELD_NUMBER: _builtins.int
    DATAITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def startPath(self) -> _containers.RepeatedCompositeFieldContainer[Global___StoreNodeKeyProto]: ...
    @_builtins.property
    def lastPath(self) -> _containers.RepeatedCompositeFieldContainer[Global___StoreNodeKeyProto]: ...
    @_builtins.property
    def historyItems(self) -> _containers.RepeatedCompositeFieldContainer[Global___StoreItemProto]: ...
    @_builtins.property
    def dataItems(self) -> _containers.RepeatedCompositeFieldContainer[Global___StoreItemProto]: ...
    def __init__(
        self,
        *,
        startPath: _abc.Iterable[Global___StoreNodeKeyProto] | None = ...,
        lastPath: _abc.Iterable[Global___StoreNodeKeyProto] | None = ...,
        historyItems: _abc.Iterable[Global___StoreItemProto] | None = ...,
        dataItems: _abc.Iterable[Global___StoreItemProto] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dataItems", b"dataItems", "historyItems", b"historyItems", "lastPath", b"lastPath", "startPath", b"startPath"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StoreItemsMessageProto: _TypeAlias = StoreItemsMessageProto  # noqa: Y015
