"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
*
The main API is `DeployService`.
"""

import DeployServiceCommon_pb2
import RhoTypes_pb2
import ServiceError_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class EventInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    @property
    def result(self) -> DeployServiceCommon_pb2.BlockEventInfo: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        result: DeployServiceCommon_pb2.BlockEventInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "result", b"result"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "result", b"result"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "result"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___EventInfoResponse: typing_extensions.TypeAlias = EventInfoResponse

@typing.final
class ExploratoryDeployResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    @property
    def result(self) -> DeployServiceCommon_pb2.DataWithBlockInfo: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        result: DeployServiceCommon_pb2.DataWithBlockInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "result", b"result"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "result", b"result"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "result"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___ExploratoryDeployResponse: typing_extensions.TypeAlias = ExploratoryDeployResponse

@typing.final
class DeployResponse(google.protobuf.message.Message):
    """doDeploy"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    result: builtins.str
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        result: builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "result", b"result"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "result", b"result"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "result"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___DeployResponse: typing_extensions.TypeAlias = DeployResponse

@typing.final
class BlockResponse(google.protobuf.message.Message):
    """getBlock"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    BLOCKINFO_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    @property
    def blockInfo(self) -> DeployServiceCommon_pb2.BlockInfo: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        blockInfo: DeployServiceCommon_pb2.BlockInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["blockInfo", b"blockInfo", "error", b"error", "message", b"message"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["blockInfo", b"blockInfo", "error", b"error", "message", b"message"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "blockInfo"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___BlockResponse: typing_extensions.TypeAlias = BlockResponse

@typing.final
class VisualizeBlocksResponse(google.protobuf.message.Message):
    """visualizeDag"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    content: builtins.str
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        content: builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["content", b"content", "error", b"error", "message", b"message"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["content", b"content", "error", b"error", "message", b"message"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "content"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___VisualizeBlocksResponse: typing_extensions.TypeAlias = VisualizeBlocksResponse

@typing.final
class MachineVerifyResponse(google.protobuf.message.Message):
    """machineVerifiableDag"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    content: builtins.str
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        content: builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["content", b"content", "error", b"error", "message", b"message"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["content", b"content", "error", b"error", "message", b"message"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "content"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___MachineVerifyResponse: typing_extensions.TypeAlias = MachineVerifyResponse

@typing.final
class BlockInfoResponse(google.protobuf.message.Message):
    """showMainChain & getBlocks"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    BLOCKINFO_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    @property
    def blockInfo(self) -> DeployServiceCommon_pb2.LightBlockInfo: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        blockInfo: DeployServiceCommon_pb2.LightBlockInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["blockInfo", b"blockInfo", "error", b"error", "message", b"message"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["blockInfo", b"blockInfo", "error", b"error", "message", b"message"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "blockInfo"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___BlockInfoResponse: typing_extensions.TypeAlias = BlockInfoResponse

@typing.final
class ListeningNameDataResponse(google.protobuf.message.Message):
    """listenForDataAtName"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    @property
    def payload(self) -> Global___ListeningNameDataPayload: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        payload: Global___ListeningNameDataPayload | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "payload", b"payload"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "payload", b"payload"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "payload"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___ListeningNameDataResponse: typing_extensions.TypeAlias = ListeningNameDataResponse

@typing.final
class ListeningNameDataPayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BLOCKINFO_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    length: builtins.int
    @property
    def blockInfo(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[DeployServiceCommon_pb2.DataWithBlockInfo]: ...
    def __init__(
        self,
        *,
        blockInfo: collections.abc.Iterable[DeployServiceCommon_pb2.DataWithBlockInfo] | None = ...,
        length: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["blockInfo", b"blockInfo", "length", b"length"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListeningNameDataPayload: typing_extensions.TypeAlias = ListeningNameDataPayload

@typing.final
class RhoDataResponse(google.protobuf.message.Message):
    """listenForDataAtPar"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    @property
    def payload(self) -> Global___RhoDataPayload: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        payload: Global___RhoDataPayload | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "payload", b"payload"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "payload", b"payload"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "payload"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___RhoDataResponse: typing_extensions.TypeAlias = RhoDataResponse

@typing.final
class RhoDataPayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAR_FIELD_NUMBER: builtins.int
    BLOCK_FIELD_NUMBER: builtins.int
    @property
    def par(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[RhoTypes_pb2.Par]: ...
    @property
    def block(self) -> DeployServiceCommon_pb2.LightBlockInfo: ...
    def __init__(
        self,
        *,
        par: collections.abc.Iterable[RhoTypes_pb2.Par] | None = ...,
        block: DeployServiceCommon_pb2.LightBlockInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["block", b"block"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["block", b"block", "par", b"par"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RhoDataPayload: typing_extensions.TypeAlias = RhoDataPayload

@typing.final
class ContinuationAtNameResponse(google.protobuf.message.Message):
    """listenForContinuationAtName"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    @property
    def payload(self) -> Global___ContinuationAtNamePayload: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        payload: Global___ContinuationAtNamePayload | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "payload", b"payload"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "payload", b"payload"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "payload"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___ContinuationAtNameResponse: typing_extensions.TypeAlias = ContinuationAtNameResponse

@typing.final
class ContinuationAtNamePayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BLOCKRESULTS_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    length: builtins.int
    @property
    def blockResults(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[DeployServiceCommon_pb2.ContinuationsWithBlockInfo]: ...
    def __init__(
        self,
        *,
        blockResults: collections.abc.Iterable[DeployServiceCommon_pb2.ContinuationsWithBlockInfo] | None = ...,
        length: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["blockResults", b"blockResults", "length", b"length"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ContinuationAtNamePayload: typing_extensions.TypeAlias = ContinuationAtNamePayload

@typing.final
class FindDeployResponse(google.protobuf.message.Message):
    """findDeploy"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    BLOCKINFO_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    @property
    def blockInfo(self) -> DeployServiceCommon_pb2.LightBlockInfo: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        blockInfo: DeployServiceCommon_pb2.LightBlockInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["blockInfo", b"blockInfo", "error", b"error", "message", b"message"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["blockInfo", b"blockInfo", "error", b"error", "message", b"message"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "blockInfo"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___FindDeployResponse: typing_extensions.TypeAlias = FindDeployResponse

@typing.final
class PrivateNamePreviewResponse(google.protobuf.message.Message):
    """previewPrivateNames"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    @property
    def payload(self) -> Global___PrivateNamePreviewPayload: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        payload: Global___PrivateNamePreviewPayload | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "payload", b"payload"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "payload", b"payload"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "payload"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___PrivateNamePreviewResponse: typing_extensions.TypeAlias = PrivateNamePreviewResponse

@typing.final
class PrivateNamePreviewPayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDS_FIELD_NUMBER: builtins.int
    @property
    def ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """a la GPrivate"""

    def __init__(
        self,
        *,
        ids: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["ids", b"ids"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PrivateNamePreviewPayload: typing_extensions.TypeAlias = PrivateNamePreviewPayload

@typing.final
class LastFinalizedBlockResponse(google.protobuf.message.Message):
    """lastFinalizedBlock"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    BLOCKINFO_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    @property
    def blockInfo(self) -> DeployServiceCommon_pb2.BlockInfo: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        blockInfo: DeployServiceCommon_pb2.BlockInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["blockInfo", b"blockInfo", "error", b"error", "message", b"message"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["blockInfo", b"blockInfo", "error", b"error", "message", b"message"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "blockInfo"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___LastFinalizedBlockResponse: typing_extensions.TypeAlias = LastFinalizedBlockResponse

@typing.final
class IsFinalizedResponse(google.protobuf.message.Message):
    """isFinalized"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    ISFINALIZED_FIELD_NUMBER: builtins.int
    isFinalized: builtins.bool
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        isFinalized: builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "isFinalized", b"isFinalized", "message", b"message"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "isFinalized", b"isFinalized", "message", b"message"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "isFinalized"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___IsFinalizedResponse: typing_extensions.TypeAlias = IsFinalizedResponse

@typing.final
class BondStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    ISBONDED_FIELD_NUMBER: builtins.int
    isBonded: builtins.bool
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        isBonded: builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "isBonded", b"isBonded", "message", b"message"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "isBonded", b"isBonded", "message", b"message"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "isBonded"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___BondStatusResponse: typing_extensions.TypeAlias = BondStatusResponse

@typing.final
class StatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> ServiceError_pb2.ServiceError: ...
    @property
    def status(self) -> DeployServiceCommon_pb2.Status: ...
    def __init__(
        self,
        *,
        error: ServiceError_pb2.ServiceError | None = ...,
        status: DeployServiceCommon_pb2.Status | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "status", b"status"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["error", b"error", "message", b"message", "status", b"status"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: typing_extensions.TypeAlias = typing.Literal["error", "status"]
    _WhichOneofArgType_message: typing_extensions.TypeAlias = typing.Literal["message", b"message"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___StatusResponse: typing_extensions.TypeAlias = StatusResponse
