# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ExternalCommunicationServiceCommon_pb2 as ExternalCommunicationServiceCommon__pb2
from . import ExternalCommunicationServiceV1_pb2 as ExternalCommunicationServiceV1__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ExternalCommunicationServiceV1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExternalCommunicationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendNotification = channel.unary_unary(
                '/casper.v1.ExternalCommunicationService/sendNotification',
                request_serializer=ExternalCommunicationServiceCommon__pb2.UpdateNotification.SerializeToString,
                response_deserializer=ExternalCommunicationServiceV1__pb2.UpdateNotificationResponse.FromString,
                _registered_method=True)


class ExternalCommunicationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExternalCommunicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.sendNotification,
                    request_deserializer=ExternalCommunicationServiceCommon__pb2.UpdateNotification.FromString,
                    response_serializer=ExternalCommunicationServiceV1__pb2.UpdateNotificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'casper.v1.ExternalCommunicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('casper.v1.ExternalCommunicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExternalCommunicationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casper.v1.ExternalCommunicationService/sendNotification',
            ExternalCommunicationServiceCommon__pb2.UpdateNotification.SerializeToString,
            ExternalCommunicationServiceV1__pb2.UpdateNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
