"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UpdateNotification(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENTHOST_FIELD_NUMBER: _builtins.int
    CLIENTPORT_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    clientHost: _builtins.str
    clientPort: _builtins.int
    payload: _builtins.str
    def __init__(
        self,
        *,
        clientHost: _builtins.str = ...,
        clientPort: _builtins.int = ...,
        payload: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clientHost", b"clientHost", "clientPort", b"clientPort", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateNotification: _TypeAlias = UpdateNotification  # noqa: Y015

@_typing.final
class UpdateNotificationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___UpdateNotificationResponse: _TypeAlias = UpdateNotificationResponse  # noqa: Y015
