# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ProposeServiceV1.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ProposeServiceV1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ServiceError_pb2 as ServiceError__pb2
from . import ProposeServiceCommon_pb2 as ProposeServiceCommon__pb2
from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ProposeServiceV1.proto\x12\tcasper.v1\x1a\x12ServiceError.proto\x1a\x1aProposeServiceCommon.proto\x1a\x15scalapb/scalapb.proto\"^\n\x0fProposeResponse\x12.\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1d.servicemodelapi.ServiceErrorH\x00\x12\x10\n\x06result\x18\x02 \x01(\tH\x00\x42\t\n\x07message\"d\n\x15ProposeResultResponse\x12.\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1d.servicemodelapi.ServiceErrorH\x00\x12\x10\n\x06result\x18\x02 \x01(\tH\x00\x42\t\n\x07message2\xa0\x01\n\x0eProposeService\x12=\n\x07propose\x12\x14.casper.ProposeQuery\x1a\x1a.casper.v1.ProposeResponse\"\x00\x12O\n\rproposeResult\x12\x1a.casper.ProposeResultQuery\x1a .casper.v1.ProposeResultResponse\"\x00\x42\x31\xe2?.\n&coop.rchain.casper.protocol.propose.v1\x10\x01(\x01H\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProposeServiceV1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\342?.\n&coop.rchain.casper.protocol.propose.v1\020\001(\001H\000'
  _globals['_PROPOSERESPONSE']._serialized_start=108
  _globals['_PROPOSERESPONSE']._serialized_end=202
  _globals['_PROPOSERESULTRESPONSE']._serialized_start=204
  _globals['_PROPOSERESULTRESPONSE']._serialized_end=304
  _globals['_PROPOSESERVICE']._serialized_start=307
  _globals['_PROPOSESERVICE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
