# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ProposeServiceCommon.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ProposeServiceCommon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aProposeServiceCommon.proto\x12\x06\x63\x61sper\x1a\x15scalapb/scalapb.proto\"7\n\x18PrintUnmatchedSendsQuery\x12\x1b\n\x13printUnmatchedSends\x18\x01 \x01(\x08\"\x14\n\x12ProposeResultQuery\"\x1f\n\x0cProposeQuery\x12\x0f\n\x07isAsync\x18\x01 \x01(\x08\x42&\xe2?#\n\x1b\x63oop.rchain.casper.protocol\x10\x01(\x01H\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProposeServiceCommon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\342?#\n\033coop.rchain.casper.protocol\020\001(\001H\000'
  _globals['_PRINTUNMATCHEDSENDSQUERY']._serialized_start=61
  _globals['_PRINTUNMATCHEDSENDSQUERY']._serialized_end=116
  _globals['_PROPOSERESULTQUERY']._serialized_start=118
  _globals['_PROPOSERESULTQUERY']._serialized_end=138
  _globals['_PROPOSEQUERY']._serialized_start=140
  _globals['_PROPOSEQUERY']._serialized_end=171
# @@protoc_insertion_point(module_scope)
