"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PrintUnmatchedSendsQuery(_message.Message):
    """TODO remove it"""

    DESCRIPTOR: _descriptor.Descriptor

    PRINTUNMATCHEDSENDS_FIELD_NUMBER: _builtins.int
    printUnmatchedSends: _builtins.bool
    def __init__(
        self,
        *,
        printUnmatchedSends: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["printUnmatchedSends", b"printUnmatchedSends"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PrintUnmatchedSendsQuery: _TypeAlias = PrintUnmatchedSendsQuery  # noqa: Y015

@_typing.final
class ProposeResultQuery(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ProposeResultQuery: _TypeAlias = ProposeResultQuery  # noqa: Y015

@_typing.final
class ProposeQuery(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ISASYNC_FIELD_NUMBER: _builtins.int
    isAsync: _builtins.bool
    def __init__(
        self,
        *,
        isAsync: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["isAsync", b"isAsync"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProposeQuery: _TypeAlias = ProposeQuery  # noqa: Y015
