"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PrintUnmatchedSendsQuery(google.protobuf.message.Message):
    """TODO remove it"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRINTUNMATCHEDSENDS_FIELD_NUMBER: builtins.int
    printUnmatchedSends: builtins.bool
    def __init__(
        self,
        *,
        printUnmatchedSends: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["printUnmatchedSends", b"printUnmatchedSends"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PrintUnmatchedSendsQuery: typing_extensions.TypeAlias = PrintUnmatchedSendsQuery

@typing.final
class ProposeResultQuery(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ProposeResultQuery: typing_extensions.TypeAlias = ProposeResultQuery

@typing.final
class ProposeQuery(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISASYNC_FIELD_NUMBER: builtins.int
    isAsync: builtins.bool
    def __init__(
        self,
        *,
        isAsync: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["isAsync", b"isAsync"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProposeQuery: typing_extensions.TypeAlias = ProposeQuery
