"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
*
Rholang Term Structure

The top level is `Par`.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Par(google.protobuf.message.Message):
    """*
    Rholang process

    For example, `@0!(1) | @2!(3) | for(x <- @0) { Nil }` has two sends
    and one receive.

    The Nil process is a `Par` with no sends, receives, etc.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SENDS_FIELD_NUMBER: builtins.int
    RECEIVES_FIELD_NUMBER: builtins.int
    NEWS_FIELD_NUMBER: builtins.int
    EXPRS_FIELD_NUMBER: builtins.int
    MATCHES_FIELD_NUMBER: builtins.int
    UNFORGEABLES_FIELD_NUMBER: builtins.int
    BUNDLES_FIELD_NUMBER: builtins.int
    CONNECTIVES_FIELD_NUMBER: builtins.int
    LOCALLYFREE_FIELD_NUMBER: builtins.int
    CONNECTIVE_USED_FIELD_NUMBER: builtins.int
    locallyFree: builtins.bytes
    connective_used: builtins.bool
    @property
    def sends(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Send]: ...
    @property
    def receives(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Receive]: ...
    @property
    def news(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___New]: ...
    @property
    def exprs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Expr]: ...
    @property
    def matches(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Match]: ...
    @property
    def unforgeables(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___GUnforgeable]:
        """unforgeable names"""

    @property
    def bundles(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Bundle]: ...
    @property
    def connectives(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Connective]: ...
    def __init__(
        self,
        *,
        sends: collections.abc.Iterable[Global___Send] | None = ...,
        receives: collections.abc.Iterable[Global___Receive] | None = ...,
        news: collections.abc.Iterable[Global___New] | None = ...,
        exprs: collections.abc.Iterable[Global___Expr] | None = ...,
        matches: collections.abc.Iterable[Global___Match] | None = ...,
        unforgeables: collections.abc.Iterable[Global___GUnforgeable] | None = ...,
        bundles: collections.abc.Iterable[Global___Bundle] | None = ...,
        connectives: collections.abc.Iterable[Global___Connective] | None = ...,
        locallyFree: builtins.bytes = ...,
        connective_used: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["bundles", b"bundles", "connective_used", b"connective_used", "connectives", b"connectives", "exprs", b"exprs", "locallyFree", b"locallyFree", "matches", b"matches", "news", b"news", "receives", b"receives", "sends", b"sends", "unforgeables", b"unforgeables"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Par: typing_extensions.TypeAlias = Par

@typing.final
class TaggedContinuation(google.protobuf.message.Message):
    """*
    Either rholang code or code built in to the interpreter.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAR_BODY_FIELD_NUMBER: builtins.int
    SCALA_BODY_REF_FIELD_NUMBER: builtins.int
    scala_body_ref: builtins.int
    @property
    def par_body(self) -> Global___ParWithRandom: ...
    def __init__(
        self,
        *,
        par_body: Global___ParWithRandom | None = ...,
        scala_body_ref: builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["par_body", b"par_body", "scala_body_ref", b"scala_body_ref", "tagged_cont", b"tagged_cont"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["par_body", b"par_body", "scala_body_ref", b"scala_body_ref", "tagged_cont", b"tagged_cont"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_tagged_cont: typing_extensions.TypeAlias = typing.Literal["par_body", "scala_body_ref"]
    _WhichOneofArgType_tagged_cont: typing_extensions.TypeAlias = typing.Literal["tagged_cont", b"tagged_cont"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_tagged_cont) -> _WhichOneofReturnType_tagged_cont | None: ...

Global___TaggedContinuation: typing_extensions.TypeAlias = TaggedContinuation

@typing.final
class ParWithRandom(google.protobuf.message.Message):
    """*
    Rholang code along with the state of a split random number
    generator for generating new unforgeable names.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BODY_FIELD_NUMBER: builtins.int
    RANDOMSTATE_FIELD_NUMBER: builtins.int
    randomState: builtins.bytes
    @property
    def body(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        body: Global___Par | None = ...,
        randomState: builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["body", b"body"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["body", b"body", "randomState", b"randomState"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ParWithRandom: typing_extensions.TypeAlias = ParWithRandom

@typing.final
class PCost(google.protobuf.message.Message):
    """*
    Cost of the performed operations.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COST_FIELD_NUMBER: builtins.int
    cost: builtins.int
    def __init__(
        self,
        *,
        cost: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["cost", b"cost"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PCost: typing_extensions.TypeAlias = PCost

@typing.final
class ListParWithRandom(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARS_FIELD_NUMBER: builtins.int
    RANDOMSTATE_FIELD_NUMBER: builtins.int
    randomState: builtins.bytes
    @property
    def pars(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Par]: ...
    def __init__(
        self,
        *,
        pars: collections.abc.Iterable[Global___Par] | None = ...,
        randomState: builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["pars", b"pars", "randomState", b"randomState"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListParWithRandom: typing_extensions.TypeAlias = ListParWithRandom

@typing.final
class Var(google.protobuf.message.Message):
    """While we use vars in both positions, when producing the normalized
    representation we need a discipline to track whether a var is a name or a
    process.
    These are DeBruijn levels
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class WildcardMsg(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    BOUND_VAR_FIELD_NUMBER: builtins.int
    FREE_VAR_FIELD_NUMBER: builtins.int
    WILDCARD_FIELD_NUMBER: builtins.int
    bound_var: builtins.int
    free_var: builtins.int
    @property
    def wildcard(self) -> Global___Var.WildcardMsg: ...
    def __init__(
        self,
        *,
        bound_var: builtins.int = ...,
        free_var: builtins.int = ...,
        wildcard: Global___Var.WildcardMsg | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["bound_var", b"bound_var", "free_var", b"free_var", "var_instance", b"var_instance", "wildcard", b"wildcard"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["bound_var", b"bound_var", "free_var", b"free_var", "var_instance", b"var_instance", "wildcard", b"wildcard"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_var_instance: typing_extensions.TypeAlias = typing.Literal["bound_var", "free_var", "wildcard"]
    _WhichOneofArgType_var_instance: typing_extensions.TypeAlias = typing.Literal["var_instance", b"var_instance"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_var_instance) -> _WhichOneofReturnType_var_instance | None: ...

Global___Var: typing_extensions.TypeAlias = Var

@typing.final
class Bundle(google.protobuf.message.Message):
    """*
    Nothing can be received from a (quoted) bundle with `readFlag = false`.
    Likeise nothing can be sent to a (quoted) bundle with `writeFlag = false`.

    If both flags are set to false, bundle allows only for equivalance check.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BODY_FIELD_NUMBER: builtins.int
    WRITEFLAG_FIELD_NUMBER: builtins.int
    READFLAG_FIELD_NUMBER: builtins.int
    writeFlag: builtins.bool
    """flag indicating whether bundle is writeable"""
    readFlag: builtins.bool
    """flag indicating whether bundle is readable"""
    @property
    def body(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        body: Global___Par | None = ...,
        writeFlag: builtins.bool = ...,
        readFlag: builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["body", b"body"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["body", b"body", "readFlag", b"readFlag", "writeFlag", b"writeFlag"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Bundle: typing_extensions.TypeAlias = Bundle

@typing.final
class Send(google.protobuf.message.Message):
    """*
    A send is written `chan!(data)` or `chan!!(data)` for a persistent send.

    Upon send, all free variables in data are substituted with their values.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHAN_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    PERSISTENT_FIELD_NUMBER: builtins.int
    LOCALLYFREE_FIELD_NUMBER: builtins.int
    CONNECTIVE_USED_FIELD_NUMBER: builtins.int
    persistent: builtins.bool
    locallyFree: builtins.bytes
    connective_used: builtins.bool
    @property
    def chan(self) -> Global___Par: ...
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Par]: ...
    def __init__(
        self,
        *,
        chan: Global___Par | None = ...,
        data: collections.abc.Iterable[Global___Par] | None = ...,
        persistent: builtins.bool = ...,
        locallyFree: builtins.bytes = ...,
        connective_used: builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["chan", b"chan"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["chan", b"chan", "connective_used", b"connective_used", "data", b"data", "locallyFree", b"locallyFree", "persistent", b"persistent"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Send: typing_extensions.TypeAlias = Send

@typing.final
class ReceiveBind(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATTERNS_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    REMAINDER_FIELD_NUMBER: builtins.int
    FREECOUNT_FIELD_NUMBER: builtins.int
    freeCount: builtins.int
    @property
    def patterns(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Par]: ...
    @property
    def source(self) -> Global___Par: ...
    @property
    def remainder(self) -> Global___Var: ...
    def __init__(
        self,
        *,
        patterns: collections.abc.Iterable[Global___Par] | None = ...,
        source: Global___Par | None = ...,
        remainder: Global___Var | None = ...,
        freeCount: builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["remainder", b"remainder", "source", b"source"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["freeCount", b"freeCount", "patterns", b"patterns", "remainder", b"remainder", "source", b"source"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReceiveBind: typing_extensions.TypeAlias = ReceiveBind

@typing.final
class BindPattern(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATTERNS_FIELD_NUMBER: builtins.int
    REMAINDER_FIELD_NUMBER: builtins.int
    FREECOUNT_FIELD_NUMBER: builtins.int
    freeCount: builtins.int
    @property
    def patterns(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Par]: ...
    @property
    def remainder(self) -> Global___Var: ...
    def __init__(
        self,
        *,
        patterns: collections.abc.Iterable[Global___Par] | None = ...,
        remainder: Global___Var | None = ...,
        freeCount: builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["remainder", b"remainder"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["freeCount", b"freeCount", "patterns", b"patterns", "remainder", b"remainder"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BindPattern: typing_extensions.TypeAlias = BindPattern

@typing.final
class ListBindPatterns(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATTERNS_FIELD_NUMBER: builtins.int
    @property
    def patterns(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___BindPattern]: ...
    def __init__(
        self,
        *,
        patterns: collections.abc.Iterable[Global___BindPattern] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["patterns", b"patterns"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListBindPatterns: typing_extensions.TypeAlias = ListBindPatterns

@typing.final
class Receive(google.protobuf.message.Message):
    """*
    A receive is written `for(binds) { body }`
    i.e. `for(patterns <- source) { body }`
    or for a persistent recieve: `for(patterns <= source) { body }`.

    It's an error for free Variable to occur more than once in a pattern.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BINDS_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    PERSISTENT_FIELD_NUMBER: builtins.int
    PEEK_FIELD_NUMBER: builtins.int
    BINDCOUNT_FIELD_NUMBER: builtins.int
    LOCALLYFREE_FIELD_NUMBER: builtins.int
    CONNECTIVE_USED_FIELD_NUMBER: builtins.int
    persistent: builtins.bool
    peek: builtins.bool
    bindCount: builtins.int
    locallyFree: builtins.bytes
    connective_used: builtins.bool
    @property
    def binds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ReceiveBind]: ...
    @property
    def body(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        binds: collections.abc.Iterable[Global___ReceiveBind] | None = ...,
        body: Global___Par | None = ...,
        persistent: builtins.bool = ...,
        peek: builtins.bool = ...,
        bindCount: builtins.int = ...,
        locallyFree: builtins.bytes = ...,
        connective_used: builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["body", b"body"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["bindCount", b"bindCount", "binds", b"binds", "body", b"body", "connective_used", b"connective_used", "locallyFree", b"locallyFree", "peek", b"peek", "persistent", b"persistent"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Receive: typing_extensions.TypeAlias = Receive

@typing.final
class New(google.protobuf.message.Message):
    """Number of variables bound in the new statement.
    For normalized form, p should not contain solely another new.
    Also for normalized form, the first use should be level+0, next use level+1
    up to level+count for the last used variable.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InjectionsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> Global___Par: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: Global___Par | None = ...,
        ) -> None: ...
        _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["value", b"value"]
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key", "value", b"value"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    BINDCOUNT_FIELD_NUMBER: builtins.int
    P_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    INJECTIONS_FIELD_NUMBER: builtins.int
    LOCALLYFREE_FIELD_NUMBER: builtins.int
    bindCount: builtins.int
    """Includes any uris listed below. This makes it easier to substitute or walk a term."""
    locallyFree: builtins.bytes
    @property
    def p(self) -> Global___Par: ...
    @property
    def uri(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """For normalization, uri-referenced variables come at the end, and in lexicographical order."""

    @property
    def injections(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, Global___Par]: ...
    def __init__(
        self,
        *,
        bindCount: builtins.int = ...,
        p: Global___Par | None = ...,
        uri: collections.abc.Iterable[builtins.str] | None = ...,
        injections: collections.abc.Mapping[builtins.str, Global___Par] | None = ...,
        locallyFree: builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p", b"p"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["bindCount", b"bindCount", "injections", b"injections", "locallyFree", b"locallyFree", "p", b"p", "uri", b"uri"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___New: typing_extensions.TypeAlias = New

@typing.final
class MatchCase(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATTERN_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    FREECOUNT_FIELD_NUMBER: builtins.int
    freeCount: builtins.int
    @property
    def pattern(self) -> Global___Par: ...
    @property
    def source(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        pattern: Global___Par | None = ...,
        source: Global___Par | None = ...,
        freeCount: builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["pattern", b"pattern", "source", b"source"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["freeCount", b"freeCount", "pattern", b"pattern", "source", b"source"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MatchCase: typing_extensions.TypeAlias = MatchCase

@typing.final
class Match(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TARGET_FIELD_NUMBER: builtins.int
    CASES_FIELD_NUMBER: builtins.int
    LOCALLYFREE_FIELD_NUMBER: builtins.int
    CONNECTIVE_USED_FIELD_NUMBER: builtins.int
    locallyFree: builtins.bytes
    connective_used: builtins.bool
    @property
    def target(self) -> Global___Par: ...
    @property
    def cases(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___MatchCase]: ...
    def __init__(
        self,
        *,
        target: Global___Par | None = ...,
        cases: collections.abc.Iterable[Global___MatchCase] | None = ...,
        locallyFree: builtins.bytes = ...,
        connective_used: builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["target", b"target"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["cases", b"cases", "connective_used", b"connective_used", "locallyFree", b"locallyFree", "target", b"target"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Match: typing_extensions.TypeAlias = Match

@typing.final
class Expr(google.protobuf.message.Message):
    """Any process may be an operand to an expression.
    Only processes equivalent to a ground process of compatible type will reduce.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    G_BOOL_FIELD_NUMBER: builtins.int
    G_INT_FIELD_NUMBER: builtins.int
    G_STRING_FIELD_NUMBER: builtins.int
    G_URI_FIELD_NUMBER: builtins.int
    G_BYTE_ARRAY_FIELD_NUMBER: builtins.int
    E_NOT_BODY_FIELD_NUMBER: builtins.int
    E_NEG_BODY_FIELD_NUMBER: builtins.int
    E_MULT_BODY_FIELD_NUMBER: builtins.int
    E_DIV_BODY_FIELD_NUMBER: builtins.int
    E_PLUS_BODY_FIELD_NUMBER: builtins.int
    E_MINUS_BODY_FIELD_NUMBER: builtins.int
    E_LT_BODY_FIELD_NUMBER: builtins.int
    E_LTE_BODY_FIELD_NUMBER: builtins.int
    E_GT_BODY_FIELD_NUMBER: builtins.int
    E_GTE_BODY_FIELD_NUMBER: builtins.int
    E_EQ_BODY_FIELD_NUMBER: builtins.int
    E_NEQ_BODY_FIELD_NUMBER: builtins.int
    E_AND_BODY_FIELD_NUMBER: builtins.int
    E_OR_BODY_FIELD_NUMBER: builtins.int
    E_VAR_BODY_FIELD_NUMBER: builtins.int
    E_LIST_BODY_FIELD_NUMBER: builtins.int
    E_TUPLE_BODY_FIELD_NUMBER: builtins.int
    E_SET_BODY_FIELD_NUMBER: builtins.int
    E_MAP_BODY_FIELD_NUMBER: builtins.int
    E_METHOD_BODY_FIELD_NUMBER: builtins.int
    E_MATCHES_BODY_FIELD_NUMBER: builtins.int
    E_PERCENT_PERCENT_BODY_FIELD_NUMBER: builtins.int
    E_PLUS_PLUS_BODY_FIELD_NUMBER: builtins.int
    E_MINUS_MINUS_BODY_FIELD_NUMBER: builtins.int
    E_MOD_BODY_FIELD_NUMBER: builtins.int
    g_bool: builtins.bool
    g_int: builtins.int
    g_string: builtins.str
    g_uri: builtins.str
    g_byte_array: builtins.bytes
    @property
    def e_not_body(self) -> Global___ENot: ...
    @property
    def e_neg_body(self) -> Global___ENeg: ...
    @property
    def e_mult_body(self) -> Global___EMult: ...
    @property
    def e_div_body(self) -> Global___EDiv: ...
    @property
    def e_plus_body(self) -> Global___EPlus: ...
    @property
    def e_minus_body(self) -> Global___EMinus: ...
    @property
    def e_lt_body(self) -> Global___ELt: ...
    @property
    def e_lte_body(self) -> Global___ELte: ...
    @property
    def e_gt_body(self) -> Global___EGt: ...
    @property
    def e_gte_body(self) -> Global___EGte: ...
    @property
    def e_eq_body(self) -> Global___EEq: ...
    @property
    def e_neq_body(self) -> Global___ENeq: ...
    @property
    def e_and_body(self) -> Global___EAnd: ...
    @property
    def e_or_body(self) -> Global___EOr: ...
    @property
    def e_var_body(self) -> Global___EVar: ...
    @property
    def e_list_body(self) -> Global___EList: ...
    @property
    def e_tuple_body(self) -> Global___ETuple: ...
    @property
    def e_set_body(self) -> Global___ESet: ...
    @property
    def e_map_body(self) -> Global___EMap: ...
    @property
    def e_method_body(self) -> Global___EMethod: ...
    @property
    def e_matches_body(self) -> Global___EMatches: ...
    @property
    def e_percent_percent_body(self) -> Global___EPercentPercent:
        """string interpolation"""

    @property
    def e_plus_plus_body(self) -> Global___EPlusPlus:
        """concatenation"""

    @property
    def e_minus_minus_body(self) -> Global___EMinusMinus:
        """set difference"""

    @property
    def e_mod_body(self) -> Global___EMod: ...
    def __init__(
        self,
        *,
        g_bool: builtins.bool = ...,
        g_int: builtins.int = ...,
        g_string: builtins.str = ...,
        g_uri: builtins.str = ...,
        g_byte_array: builtins.bytes = ...,
        e_not_body: Global___ENot | None = ...,
        e_neg_body: Global___ENeg | None = ...,
        e_mult_body: Global___EMult | None = ...,
        e_div_body: Global___EDiv | None = ...,
        e_plus_body: Global___EPlus | None = ...,
        e_minus_body: Global___EMinus | None = ...,
        e_lt_body: Global___ELt | None = ...,
        e_lte_body: Global___ELte | None = ...,
        e_gt_body: Global___EGt | None = ...,
        e_gte_body: Global___EGte | None = ...,
        e_eq_body: Global___EEq | None = ...,
        e_neq_body: Global___ENeq | None = ...,
        e_and_body: Global___EAnd | None = ...,
        e_or_body: Global___EOr | None = ...,
        e_var_body: Global___EVar | None = ...,
        e_list_body: Global___EList | None = ...,
        e_tuple_body: Global___ETuple | None = ...,
        e_set_body: Global___ESet | None = ...,
        e_map_body: Global___EMap | None = ...,
        e_method_body: Global___EMethod | None = ...,
        e_matches_body: Global___EMatches | None = ...,
        e_percent_percent_body: Global___EPercentPercent | None = ...,
        e_plus_plus_body: Global___EPlusPlus | None = ...,
        e_minus_minus_body: Global___EMinusMinus | None = ...,
        e_mod_body: Global___EMod | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["e_and_body", b"e_and_body", "e_div_body", b"e_div_body", "e_eq_body", b"e_eq_body", "e_gt_body", b"e_gt_body", "e_gte_body", b"e_gte_body", "e_list_body", b"e_list_body", "e_lt_body", b"e_lt_body", "e_lte_body", b"e_lte_body", "e_map_body", b"e_map_body", "e_matches_body", b"e_matches_body", "e_method_body", b"e_method_body", "e_minus_body", b"e_minus_body", "e_minus_minus_body", b"e_minus_minus_body", "e_mod_body", b"e_mod_body", "e_mult_body", b"e_mult_body", "e_neg_body", b"e_neg_body", "e_neq_body", b"e_neq_body", "e_not_body", b"e_not_body", "e_or_body", b"e_or_body", "e_percent_percent_body", b"e_percent_percent_body", "e_plus_body", b"e_plus_body", "e_plus_plus_body", b"e_plus_plus_body", "e_set_body", b"e_set_body", "e_tuple_body", b"e_tuple_body", "e_var_body", b"e_var_body", "expr_instance", b"expr_instance", "g_bool", b"g_bool", "g_byte_array", b"g_byte_array", "g_int", b"g_int", "g_string", b"g_string", "g_uri", b"g_uri"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["e_and_body", b"e_and_body", "e_div_body", b"e_div_body", "e_eq_body", b"e_eq_body", "e_gt_body", b"e_gt_body", "e_gte_body", b"e_gte_body", "e_list_body", b"e_list_body", "e_lt_body", b"e_lt_body", "e_lte_body", b"e_lte_body", "e_map_body", b"e_map_body", "e_matches_body", b"e_matches_body", "e_method_body", b"e_method_body", "e_minus_body", b"e_minus_body", "e_minus_minus_body", b"e_minus_minus_body", "e_mod_body", b"e_mod_body", "e_mult_body", b"e_mult_body", "e_neg_body", b"e_neg_body", "e_neq_body", b"e_neq_body", "e_not_body", b"e_not_body", "e_or_body", b"e_or_body", "e_percent_percent_body", b"e_percent_percent_body", "e_plus_body", b"e_plus_body", "e_plus_plus_body", b"e_plus_plus_body", "e_set_body", b"e_set_body", "e_tuple_body", b"e_tuple_body", "e_var_body", b"e_var_body", "expr_instance", b"expr_instance", "g_bool", b"g_bool", "g_byte_array", b"g_byte_array", "g_int", b"g_int", "g_string", b"g_string", "g_uri", b"g_uri"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_expr_instance: typing_extensions.TypeAlias = typing.Literal["g_bool", "g_int", "g_string", "g_uri", "g_byte_array", "e_not_body", "e_neg_body", "e_mult_body", "e_div_body", "e_plus_body", "e_minus_body", "e_lt_body", "e_lte_body", "e_gt_body", "e_gte_body", "e_eq_body", "e_neq_body", "e_and_body", "e_or_body", "e_var_body", "e_list_body", "e_tuple_body", "e_set_body", "e_map_body", "e_method_body", "e_matches_body", "e_percent_percent_body", "e_plus_plus_body", "e_minus_minus_body", "e_mod_body"]
    _WhichOneofArgType_expr_instance: typing_extensions.TypeAlias = typing.Literal["expr_instance", b"expr_instance"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_expr_instance) -> _WhichOneofReturnType_expr_instance | None: ...

Global___Expr: typing_extensions.TypeAlias = Expr

@typing.final
class EList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PS_FIELD_NUMBER: builtins.int
    LOCALLYFREE_FIELD_NUMBER: builtins.int
    CONNECTIVE_USED_FIELD_NUMBER: builtins.int
    REMAINDER_FIELD_NUMBER: builtins.int
    locallyFree: builtins.bytes
    connective_used: builtins.bool
    @property
    def ps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Par]: ...
    @property
    def remainder(self) -> Global___Var: ...
    def __init__(
        self,
        *,
        ps: collections.abc.Iterable[Global___Par] | None = ...,
        locallyFree: builtins.bytes = ...,
        connective_used: builtins.bool = ...,
        remainder: Global___Var | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["remainder", b"remainder"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["connective_used", b"connective_used", "locallyFree", b"locallyFree", "ps", b"ps", "remainder", b"remainder"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EList: typing_extensions.TypeAlias = EList

@typing.final
class ETuple(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PS_FIELD_NUMBER: builtins.int
    LOCALLYFREE_FIELD_NUMBER: builtins.int
    CONNECTIVE_USED_FIELD_NUMBER: builtins.int
    locallyFree: builtins.bytes
    connective_used: builtins.bool
    @property
    def ps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Par]: ...
    def __init__(
        self,
        *,
        ps: collections.abc.Iterable[Global___Par] | None = ...,
        locallyFree: builtins.bytes = ...,
        connective_used: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["connective_used", b"connective_used", "locallyFree", b"locallyFree", "ps", b"ps"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ETuple: typing_extensions.TypeAlias = ETuple

@typing.final
class ESet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PS_FIELD_NUMBER: builtins.int
    LOCALLYFREE_FIELD_NUMBER: builtins.int
    CONNECTIVE_USED_FIELD_NUMBER: builtins.int
    REMAINDER_FIELD_NUMBER: builtins.int
    locallyFree: builtins.bytes
    connective_used: builtins.bool
    @property
    def ps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Par]: ...
    @property
    def remainder(self) -> Global___Var: ...
    def __init__(
        self,
        *,
        ps: collections.abc.Iterable[Global___Par] | None = ...,
        locallyFree: builtins.bytes = ...,
        connective_used: builtins.bool = ...,
        remainder: Global___Var | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["remainder", b"remainder"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["connective_used", b"connective_used", "locallyFree", b"locallyFree", "ps", b"ps", "remainder", b"remainder"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ESet: typing_extensions.TypeAlias = ESet

@typing.final
class EMap(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KVS_FIELD_NUMBER: builtins.int
    LOCALLYFREE_FIELD_NUMBER: builtins.int
    CONNECTIVE_USED_FIELD_NUMBER: builtins.int
    REMAINDER_FIELD_NUMBER: builtins.int
    locallyFree: builtins.bytes
    connective_used: builtins.bool
    @property
    def kvs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___KeyValuePair]: ...
    @property
    def remainder(self) -> Global___Var: ...
    def __init__(
        self,
        *,
        kvs: collections.abc.Iterable[Global___KeyValuePair] | None = ...,
        locallyFree: builtins.bytes = ...,
        connective_used: builtins.bool = ...,
        remainder: Global___Var | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["remainder", b"remainder"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["connective_used", b"connective_used", "kvs", b"kvs", "locallyFree", b"locallyFree", "remainder", b"remainder"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EMap: typing_extensions.TypeAlias = EMap

@typing.final
class EMethod(google.protobuf.message.Message):
    """*
    `target.method(arguments)`
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METHODNAME_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    ARGUMENTS_FIELD_NUMBER: builtins.int
    LOCALLYFREE_FIELD_NUMBER: builtins.int
    CONNECTIVE_USED_FIELD_NUMBER: builtins.int
    methodName: builtins.str
    locallyFree: builtins.bytes
    connective_used: builtins.bool
    @property
    def target(self) -> Global___Par: ...
    @property
    def arguments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Par]: ...
    def __init__(
        self,
        *,
        methodName: builtins.str = ...,
        target: Global___Par | None = ...,
        arguments: collections.abc.Iterable[Global___Par] | None = ...,
        locallyFree: builtins.bytes = ...,
        connective_used: builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["target", b"target"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["arguments", b"arguments", "connective_used", b"connective_used", "locallyFree", b"locallyFree", "methodName", b"methodName", "target", b"target"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EMethod: typing_extensions.TypeAlias = EMethod

@typing.final
class KeyValuePair(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    @property
    def key(self) -> Global___Par: ...
    @property
    def value(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        key: Global___Par | None = ...,
        value: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key", "value", b"value"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key", "value", b"value"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KeyValuePair: typing_extensions.TypeAlias = KeyValuePair

@typing.final
class EVar(google.protobuf.message.Message):
    """A variable used as a var should be bound in a process context, not a name
    context. For example:
    `for (@x <- c1; @y <- c2) { z!(x + y) }` is fine, but
    `for (x <- c1; y <- c2) { z!(x + y) }` should raise an error.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    V_FIELD_NUMBER: builtins.int
    @property
    def v(self) -> Global___Var: ...
    def __init__(
        self,
        *,
        v: Global___Var | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["v", b"v"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["v", b"v"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EVar: typing_extensions.TypeAlias = EVar

@typing.final
class ENot(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P_FIELD_NUMBER: builtins.int
    @property
    def p(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p", b"p"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p", b"p"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ENot: typing_extensions.TypeAlias = ENot

@typing.final
class ENeg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P_FIELD_NUMBER: builtins.int
    @property
    def p(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p", b"p"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p", b"p"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ENeg: typing_extensions.TypeAlias = ENeg

@typing.final
class EMult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EMult: typing_extensions.TypeAlias = EMult

@typing.final
class EDiv(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EDiv: typing_extensions.TypeAlias = EDiv

@typing.final
class EMod(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EMod: typing_extensions.TypeAlias = EMod

@typing.final
class EPlus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EPlus: typing_extensions.TypeAlias = EPlus

@typing.final
class EMinus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EMinus: typing_extensions.TypeAlias = EMinus

@typing.final
class ELt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ELt: typing_extensions.TypeAlias = ELt

@typing.final
class ELte(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ELte: typing_extensions.TypeAlias = ELte

@typing.final
class EGt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EGt: typing_extensions.TypeAlias = EGt

@typing.final
class EGte(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EGte: typing_extensions.TypeAlias = EGte

@typing.final
class EEq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EEq: typing_extensions.TypeAlias = EEq

@typing.final
class ENeq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ENeq: typing_extensions.TypeAlias = ENeq

@typing.final
class EAnd(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EAnd: typing_extensions.TypeAlias = EAnd

@typing.final
class EOr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EOr: typing_extensions.TypeAlias = EOr

@typing.final
class EMatches(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TARGET_FIELD_NUMBER: builtins.int
    PATTERN_FIELD_NUMBER: builtins.int
    @property
    def target(self) -> Global___Par: ...
    @property
    def pattern(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        target: Global___Par | None = ...,
        pattern: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["pattern", b"pattern", "target", b"target"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["pattern", b"pattern", "target", b"target"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EMatches: typing_extensions.TypeAlias = EMatches

@typing.final
class EPercentPercent(google.protobuf.message.Message):
    """*
    String interpolation

    `"Hello, {name}" %% {"name": "Bob"}` denotes `"Hello, Bob"`
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EPercentPercent: typing_extensions.TypeAlias = EPercentPercent

@typing.final
class EPlusPlus(google.protobuf.message.Message):
    """Concatenation"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EPlusPlus: typing_extensions.TypeAlias = EPlusPlus

@typing.final
class EMinusMinus(google.protobuf.message.Message):
    """Set difference"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> Global___Par: ...
    @property
    def p2(self) -> Global___Par: ...
    def __init__(
        self,
        *,
        p1: Global___Par | None = ...,
        p2: Global___Par | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["p1", b"p1", "p2", b"p2"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EMinusMinus: typing_extensions.TypeAlias = EMinusMinus

@typing.final
class Connective(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONN_AND_BODY_FIELD_NUMBER: builtins.int
    CONN_OR_BODY_FIELD_NUMBER: builtins.int
    CONN_NOT_BODY_FIELD_NUMBER: builtins.int
    VAR_REF_BODY_FIELD_NUMBER: builtins.int
    CONN_BOOL_FIELD_NUMBER: builtins.int
    CONN_INT_FIELD_NUMBER: builtins.int
    CONN_STRING_FIELD_NUMBER: builtins.int
    CONN_URI_FIELD_NUMBER: builtins.int
    CONN_BYTE_ARRAY_FIELD_NUMBER: builtins.int
    conn_bool: builtins.bool
    conn_int: builtins.bool
    conn_string: builtins.bool
    conn_uri: builtins.bool
    conn_byte_array: builtins.bool
    @property
    def conn_and_body(self) -> Global___ConnectiveBody: ...
    @property
    def conn_or_body(self) -> Global___ConnectiveBody: ...
    @property
    def conn_not_body(self) -> Global___Par: ...
    @property
    def var_ref_body(self) -> Global___VarRef: ...
    def __init__(
        self,
        *,
        conn_and_body: Global___ConnectiveBody | None = ...,
        conn_or_body: Global___ConnectiveBody | None = ...,
        conn_not_body: Global___Par | None = ...,
        var_ref_body: Global___VarRef | None = ...,
        conn_bool: builtins.bool = ...,
        conn_int: builtins.bool = ...,
        conn_string: builtins.bool = ...,
        conn_uri: builtins.bool = ...,
        conn_byte_array: builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["conn_and_body", b"conn_and_body", "conn_bool", b"conn_bool", "conn_byte_array", b"conn_byte_array", "conn_int", b"conn_int", "conn_not_body", b"conn_not_body", "conn_or_body", b"conn_or_body", "conn_string", b"conn_string", "conn_uri", b"conn_uri", "connective_instance", b"connective_instance", "var_ref_body", b"var_ref_body"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["conn_and_body", b"conn_and_body", "conn_bool", b"conn_bool", "conn_byte_array", b"conn_byte_array", "conn_int", b"conn_int", "conn_not_body", b"conn_not_body", "conn_or_body", b"conn_or_body", "conn_string", b"conn_string", "conn_uri", b"conn_uri", "connective_instance", b"connective_instance", "var_ref_body", b"var_ref_body"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_connective_instance: typing_extensions.TypeAlias = typing.Literal["conn_and_body", "conn_or_body", "conn_not_body", "var_ref_body", "conn_bool", "conn_int", "conn_string", "conn_uri", "conn_byte_array"]
    _WhichOneofArgType_connective_instance: typing_extensions.TypeAlias = typing.Literal["connective_instance", b"connective_instance"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_connective_instance) -> _WhichOneofReturnType_connective_instance | None: ...

Global___Connective: typing_extensions.TypeAlias = Connective

@typing.final
class VarRef(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    DEPTH_FIELD_NUMBER: builtins.int
    index: builtins.int
    depth: builtins.int
    def __init__(
        self,
        *,
        index: builtins.int = ...,
        depth: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["depth", b"depth", "index", b"index"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VarRef: typing_extensions.TypeAlias = VarRef

@typing.final
class ConnectiveBody(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PS_FIELD_NUMBER: builtins.int
    @property
    def ps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Par]: ...
    def __init__(
        self,
        *,
        ps: collections.abc.Iterable[Global___Par] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["ps", b"ps"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectiveBody: typing_extensions.TypeAlias = ConnectiveBody

@typing.final
class DeployId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIG_FIELD_NUMBER: builtins.int
    sig: builtins.bytes
    def __init__(
        self,
        *,
        sig: builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["sig", b"sig"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeployId: typing_extensions.TypeAlias = DeployId

@typing.final
class DeployerId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLICKEY_FIELD_NUMBER: builtins.int
    publicKey: builtins.bytes
    def __init__(
        self,
        *,
        publicKey: builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["publicKey", b"publicKey"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeployerId: typing_extensions.TypeAlias = DeployerId

@typing.final
class GUnforgeable(google.protobuf.message.Message):
    """Unforgeable names resulting from `new x { ... }`
    These should only occur as the program is being evaluated. There is no way in
    the grammar to construct them.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    G_PRIVATE_BODY_FIELD_NUMBER: builtins.int
    G_DEPLOY_ID_BODY_FIELD_NUMBER: builtins.int
    G_DEPLOYER_ID_BODY_FIELD_NUMBER: builtins.int
    G_SYS_AUTH_TOKEN_BODY_FIELD_NUMBER: builtins.int
    @property
    def g_private_body(self) -> Global___GPrivate: ...
    @property
    def g_deploy_id_body(self) -> Global___GDeployId: ...
    @property
    def g_deployer_id_body(self) -> Global___GDeployerId: ...
    @property
    def g_sys_auth_token_body(self) -> Global___GSysAuthToken: ...
    def __init__(
        self,
        *,
        g_private_body: Global___GPrivate | None = ...,
        g_deploy_id_body: Global___GDeployId | None = ...,
        g_deployer_id_body: Global___GDeployerId | None = ...,
        g_sys_auth_token_body: Global___GSysAuthToken | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["g_deploy_id_body", b"g_deploy_id_body", "g_deployer_id_body", b"g_deployer_id_body", "g_private_body", b"g_private_body", "g_sys_auth_token_body", b"g_sys_auth_token_body", "unf_instance", b"unf_instance"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["g_deploy_id_body", b"g_deploy_id_body", "g_deployer_id_body", b"g_deployer_id_body", "g_private_body", b"g_private_body", "g_sys_auth_token_body", b"g_sys_auth_token_body", "unf_instance", b"unf_instance"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_unf_instance: typing_extensions.TypeAlias = typing.Literal["g_private_body", "g_deploy_id_body", "g_deployer_id_body", "g_sys_auth_token_body"]
    _WhichOneofArgType_unf_instance: typing_extensions.TypeAlias = typing.Literal["unf_instance", b"unf_instance"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_unf_instance) -> _WhichOneofReturnType_unf_instance | None: ...

Global___GUnforgeable: typing_extensions.TypeAlias = GUnforgeable

@typing.final
class GPrivate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.bytes
    def __init__(
        self,
        *,
        id: builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["id", b"id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GPrivate: typing_extensions.TypeAlias = GPrivate

@typing.final
class GDeployId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIG_FIELD_NUMBER: builtins.int
    sig: builtins.bytes
    def __init__(
        self,
        *,
        sig: builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["sig", b"sig"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GDeployId: typing_extensions.TypeAlias = GDeployId

@typing.final
class GDeployerId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLICKEY_FIELD_NUMBER: builtins.int
    publicKey: builtins.bytes
    def __init__(
        self,
        *,
        publicKey: builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["publicKey", b"publicKey"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GDeployerId: typing_extensions.TypeAlias = GDeployerId

@typing.final
class GSysAuthToken(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GSysAuthToken: typing_extensions.TypeAlias = GSysAuthToken
